help = "Commands for interacting with the git client on the client host."

# Integrated to the carburator
########################################################

# Clone
#
[command.clone]
help = "Clone repository from the given path."
platform = ["Client"]
command = "git clone {{ path }} {{ target }}"

[command.clone.args.path]
help = "Path, remote or local to the git repository"
value_is = "String"
arg_index = 1
required = true

[command.clone.args.target]
help = "Target directory on localhost where repository will be cloned to."
value_is = "String"
arg_index = 2
required = true

# Upgrage
#
[command.upgrade]
help = "Upgrade changes from remote repository into the local one. (packages)"
platform = ["Client"]
executor = "package/upgrade"

[command.upgrade.args.path]
help = "Remote path to the repository"
value_is = "String"
arg_index = 1
required = true

[command.upgrade.args.branch]
help = "Remote repository branch to upgrade from. (defaults to 'main')"
value_is = "String"
arg_index = 2
required = false

# Push
#
[command.push]
help = "Push local changes to remote repository."
platform = ["Client"]
command = "git -C {{ path }} push {{ branch_remote | default('main') }} {{ branch_local | default('main') }}"

[command.push.args.path]
help = "Remote path to the repository"
value_is = "String"
arg_index = 1
required = true

[command.push.args.branch_remote]
help = "Remote repository branch to push to. (defaults to 'main')"
value_is = "String"
arg_index = 2
required = false

[command.push.args.branch_local]
help = "Local repository branch to push from. (defaults to 'main')"
value_is = "String"
arg_index = 3
required = false

########################################################
